### PR TITLE
Allow installation on PHP 8.

### PR DESCRIPTION
**Pull request by michaelaguiar**

### CODE REVIEW

**Comment by freekmurze** [comment]
Please also let the tests run on PHP 8

**Comment by freekmurze** [comment]
Could you take care of the failing tests?

**Comment by michaelaguiar** [comment]
Yep! Working on these now. Will submit again once fixed.

**Comment by neochief** [comment]
@michaelaguiar thanks for taking care of it! Any updates?

**Comment by michaelaguiar** [comment]
Sorry for the delay! I'll see if I can finish up this update today and get the PR in.

**Comment by Nielsvanpach** [comment]
Already done in https://github.com/spatie/laravel-server-monitor/pull/115

**Pull request closed without merging**
