### PR TITLE
Add threshold for dispkace's alerts

### PR DESCRIPTION
**Pull request by ptondereau**
This PR just add an entry in config file to configure thresholds alert for diskpace.

### CODE REVIEW

**Comment by freekmurze** [comment]
Could you remove all changes unrelated to adding the threshold to the config file?

**Comment by ptondereau** [comment]
@freekmurze done

**Comment by freekmurze** [comment]
For people using the old version of the config file this change will break their monitor. Could you make sure the previous values are used in the check if the new keys are not present in the config file?

**Comment by ptondereau** [comment]
@freekmurze this should do the trick. Thanks for the suggest

**Comment by freekmurze** [comment]
Thank you!

**Pull request merged**
